# Generated by Django 3.0.2 on 2020-01-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_desc', models.CharField(max_length=100)),
                ('rest_date', models.CharField(max_length=100)),
                ('parking_info', models.CharField(max_length=100)),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
